name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.0.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            EXT: ""
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            EXT: ""
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            EXT: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up version variable
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} \
          go build -ldflags="-s -w -X main.Version=${{ env.VERSION }}" -o saferm${{ matrix.EXT }} .

      - name: Rename binary for release
        run: |
          if [ "${{ matrix.GOOS }}" = "windows" ]; then
            mv saferm${{ matrix.EXT }} saferm-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.exe
          else
            mv saferm${{ matrix.EXT }} saferm-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: saferm-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: |
            saferm-${{ matrix.GOOS }}-${{ matrix.GOARCH }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/saferm*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
